<a href="https://colab.research.google.com/github/AnndyLibeMoore/Python_My_Learn/blob/main/Creando_Rangos_valor_tratamiento_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
datos = pd.read_csv('alquiler.csv',sep= ';')
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200.0,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
4,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
6,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
7,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
8,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
9,Local comercial,Pachacámac,0,3,0,695,35000.0,19193.0,3030.0

In [3]:
#agruparemos por cantidades de cuartos q tenga
#el inmueble y asi ver las frecuencias

# quiero agrupar
#1 y 2 cuartos
# 3 y 4
# 5 y 6
#7 ó más

'''
para ello crearemos condicionales para esta seleccion
como haciendo cortes, para obtener los registrps de
1 y 2 cuartos los limites serian desde 0 - 2 y asi.
'''

clases =  [0, 2, 4, 6, 100]

In [4]:
#ahora llamremos cut e
#este metodo realizara los cortes
#le diremos q tome los datos de la columna Cuartos
#y q tome como base para acer los cortes la
#lista clases

cuartos = pd.cut(datos.Cuartos, clases)
cuartos

0        (0.0, 2.0]
1        (0.0, 2.0]
2               NaN
3        (0.0, 2.0]
4        (0.0, 2.0]
            ...
32955           NaN
32956    (2.0, 4.0]
32957    (0.0, 2.0]
32958    (0.0, 2.0]
32959           NaN
Name: Cuartos, Length: 32960, dtype: category
Categories (4, interval[int64, right]): [(0, 2] < (2, 4] < (4, 6] < (6, 100]]

In [ ]:
'''
bien aqui genero una series, de categorias, asi q
recorre el df y en seguida le pone a qué categoria
pertenece

bien aqui hay inmuebles q tienen 0 cuartos y
en nuestras categorias el 0 no es considerado
asi  q lo deja nulo

veamos las frecuencias
'''

In [5]:
pd.value_counts(cuartos)

Cuartos
(0, 2]      12419
(2, 4]       9894
(4, 6]        709
(6, 100]       87
Name: count, dtype: int64

In [6]:
#generaremos nuestras etiquetas

label = ['1 y 2 cuartos', '3 y 4 cuartos', '5 y 6 cuartos', '7 ó más cuartos' ]

In [7]:
#bien ahora al llmar al metodo llmare
#o le pondre las etiquetas

cuartos = pd.cut(datos.Cuartos, clases, labels = label )

In [9]:
pd.value_counts(cuartos)

Cuartos
1 y 2 cuartos      12419
3 y 4 cuartos       9894
5 y 6 cuartos        709
7 ó más cuartos       87
Name: count, dtype: int64

In [11]:
#vamos a incluir los valores de 0 cuartos
#dentro de la primer categoria

cuartos = pd.cut(datos.Cuartos, clases, labels = label, include_lowest= True )
cuartos

0        1 y 2 cuartos
1        1 y 2 cuartos
2        1 y 2 cuartos
3        1 y 2 cuartos
4        1 y 2 cuartos
             ...
32955    1 y 2 cuartos
32956    3 y 4 cuartos
32957    1 y 2 cuartos
32958    1 y 2 cuartos
32959    1 y 2 cuartos
Name: Cuartos, Length: 32960, dtype: category
Categories (4, object): ['1 y 2 cuartos' < '3 y 4 cuartos' < '5 y 6 cuartos' < '7 ó más cuartos']